# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoezidsettings',
            name='ezid_endpoint_url',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repoezidsettings',
            name='ezid_password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repoezidsettings',
            name='ezid_username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
